
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package c2.gramaticas;

/** CUP generated class containing symbol constants. */
public class Simbolos_chtml {
  /* terminals */
  public static final int grupo = 19;
  public static final int ancho = 21;
  public static final int id2 = 23;
  public static final int cadena = 26;
  public static final int ruta = 17;
  public static final int bodyo = 10;
  public static final int cjso = 12;
  public static final int ccsso = 14;
  public static final int chtmlo = 2;
  public static final int panelo = 8;
  public static final int alto = 20;
  public static final int num = 24;
  public static final int bodyc = 11;
  public static final int caracter = 25;
  public static final int cjsc = 13;
  public static final int chtmlc = 3;
  public static final int ccssc = 15;
  public static final int panelc = 9;
  public static final int tituloo = 6;
  public static final int heado = 4;
  public static final int EOF = 0;
  public static final int alineado = 22;
  public static final int id = 18;
  public static final int error = 1;
  public static final int tituloc = 7;
  public static final int headc = 5;
  public static final int fondo = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "chtmlo",
  "chtmlc",
  "heado",
  "headc",
  "tituloo",
  "tituloc",
  "panelo",
  "panelc",
  "bodyo",
  "bodyc",
  "cjso",
  "cjsc",
  "ccsso",
  "ccssc",
  "fondo",
  "ruta",
  "id",
  "grupo",
  "alto",
  "ancho",
  "alineado",
  "id2",
  "num",
  "caracter",
  "cadena"
  };
}

